guests = ["Adrian Kowalski", "Mateusz Adamkowski", "Tomasz Narozny"]
invitation = ", witaj - zapraszam Cię na obiad"
print(guests[0] + invitation)
print(guests[1] + invitation)
print(guests[2] + invitation)
nieprzyjdzie = guests.pop(1)
print('nie pojawi sie: ' + nieprzyjdzie)
guests.append('Maciej Donkiel')
print(guests)
print(guests[0] + invitation)
print(guests[1] + invitation)
print(guests[2] + invitation)
print("Znalazlem wiekszy stol, zmiesci sie wiecej osob.")
guests.insert(0, 'Dominik Drak')
print(guests)
guests.insert(2, 'Mieczyński')
print(guests)
guests.append('Andrzej Wojtek')
print(guests)
print("Niestety większy stół nie zstanie dostarczony, na obiaz zostana zaproszone tylko dwie osoby.")
nieprzyjdzie = guests.pop(0)
print(nieprzyjdzie + ' Bardzo przepraszam, ale nie moge Cie zaprosic')
print('Aktualna lista zaproszonych: ' + ', '.join(guests))
nieprzyjdzie = guests.pop(4)
print(nieprzyjdzie + ' Bardzo przepraszam, ale nie moge Cie zaprosic')
print('Aktualna lista zaproszonych: ' + ', '.join(guests))
nieprzyjdzie = guests.pop(0)
print(nieprzyjdzie + ' Bardzo przepraszam, ale nie moge Cie zaprosic')
print('Aktualna lista zaproszonych: ' + ', '.join(guests))
nieprzyjdzie = guests.pop(0)
print(nieprzyjdzie + ' Bardzo przepraszam, ale nie moge Cie zaprosic')
print('Aktualna lista zaproszonych: ' + ', '.join(guests))
print(len(guests))
print('Niezmiernie mi miło ' + guests[0] + ' zaprosic Cię na obiad')
print('Niezmiernie mi miło ' + guests[1] + ' zaprosic Cię na obiad')
del guests[0]
print(guests)
del guests[0]
print(guests)