cars = ['bmw']
cars.append('audi')
cars.append('toyota')
cars.append('subaru')
print(cars)
cars.sort()
print(cars)
cars.sort(reverse=True)
print(cars)
cars = ['bmw', 'audi', 'toyota', 'subaru']
print("Oto lista początkowa: ")
print(cars)
print("/nOto lista posortowana: ")
print(sorted(cars))
print("Oto lista początkowa ponownie: ")
print(cars)
print("***")
cars.reverse()
print(cars)
cars.reverse()
print(cars)
print(len(cars))